### ISSUE TITLE
[CONTRIBUTION] New Recipe

### ISSUE THREAD

**Issue by Vbitz** [Vbitz/issue-test#10]
## Recipe Contribution

Please paste your recipe YAML below:

```yaml
name: dasdasd
description: A sample recipe
ingredients:
  - item1
  - item2
steps:
  - Step 1
  - Step 2
```
