### ISSUE TITLE
[CONTRIBUTION] New Recipe

### ISSUE THREAD

**Issue by Vbitz** [Vbitz/issue-test#11]
## Recipe Contribution

Please paste your recipe YAML below:

```yaml
name: dasdasd
description: A sample recipe
hello:
  - Step 1
  - Step 2
```
