### ISSUE TITLE
New Recipe Contribution

### ISSUE THREAD

**Issue by Vbitz** [Vbitz/issue-test#3]
## Recipe Contribution

Please paste your recipe YAML below:

```yaml
name: example-recipe
description: A sample recipe
ingredients:
  - item1
  - item2
steps:
  - Step 1
  - Step 2
```
