### ISSUE TITLE
Update Recipe\

### ISSUE THREAD

**Issue by Vbitz** [Vbitz/issue-test#4]
## Recipe Contribution

Please paste your recipe YAML below:

```yaml
name: example-recipe
description: A sample recipe
ingredients:
  - item2
steps:
  - Step 2
```
