### ISSUE TITLE
New Recipe Contribution

### ISSUE THREAD

**Issue by micmas** [Vbitz/issue-test#5]
## Recipe Contribution

Please paste your recipe YAML below:

```yaml
name: table
description: A sample recipe
ingredients:
  - item1
  - item2
steps:
  - Step 1
  - Step 2
```
