### ISSUE TITLE
[CONTRIBUTION] New Recipe

### ISSUE THREAD

**Issue by Vbitz** [Vbitz/issue-test#8]
## Recipe Contribution

Please paste your recipe YAML below:

```yaml
name: hello
description: A sample recipe
ingredients:
  - item1
  - item2
```
