### ISSUE TITLE
[CONTRIBUTION] New Recipe

### ISSUE THREAD

**Issue by micmas** [Vbitz/issue-test#9]
## Recipe Contribution

Please paste your recipe YAML below:

```yaml
name: table1
description: A sample recipe
ingredients:
  - item1
  - item2
steps:
  - Step 1
  - Step 2
```
